In [7]:
import pandas as pd
from alpha_vantage.fundamentaldata import FundamentalData

In [10]:
df = pd.read_csv("C:/Users/patel/Downloads/data/survey_results_public.csv")
key_path = "C:/Users/patel/OneDrive/Desktop/top secret.txt"
with open(key_path, "r") as f:
    key = f.read()
    key = key[23:]

AVobj = FundamentalData(key=key, output_format="pandas")

In [35]:
pd.set_option("display.max_columns", 38)
pd.set_option("display.max_rows", 100)

In [13]:
balsheet= AVobj.get_balance_sheet_annual(symbol="msft")

In [36]:
balsheetDF = balsheet[0]
display(balsheetDF.shape)
display(balsheetDF.info())
display(balsheetDF)

(15, 38)

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 15 entries, 1970-01-01 00:00:00 to 1970-01-01 00:00:00.000000014
Data columns (total 38 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   fiscalDateEnding                        15 non-null     object
 1   reportedCurrency                        15 non-null     object
 2   totalAssets                             15 non-null     object
 3   totalCurrentAssets                      15 non-null     object
 4   cashAndCashEquivalentsAtCarryingValue   15 non-null     object
 5   cashAndShortTermInvestments             15 non-null     object
 6   inventory                               15 non-null     object
 7   currentNetReceivables                   15 non-null     object
 8   totalNonCurrentAssets                   15 non-null     object
 9   propertyPlantEquipment                  15 non-null     object
 10  accumulatedDepreciationAmortizationPPE  15 non-null     object
 11  intangibleAssets                        15 non-null     object
 12  intangibleAssetsExcludingGoodwill       15 non-null     object
 13  goodwill                                15 non-null     object
 14  investments                             15 non-null     object
 15  longTermInvestments                     15 non-null     object
 16  shortTermInvestments                    15 non-null     object
 17  otherCurrentAssets                      15 non-null     object
 18  otherNonCurrentAssets                   15 non-null     object
 19  totalLiabilities                        15 non-null     object
 20  totalCurrentLiabilities                 15 non-null     object
 21  currentAccountsPayable                  15 non-null     object
 22  deferredRevenue                         15 non-null     object
 23  currentDebt                             15 non-null     object
 24  shortTermDebt                           15 non-null     object
 25  totalNonCurrentLiabilities              15 non-null     object
 26  capitalLeaseObligations                 15 non-null     object
 27  longTermDebt                            15 non-null     object
 28  currentLongTermDebt                     15 non-null     object
 29  longTermDebtNoncurrent                  15 non-null     object
 30  shortLongTermDebtTotal                  15 non-null     object
 31  otherCurrentLiabilities                 15 non-null     object
 32  otherNonCurrentLiabilities              15 non-null     object
 33  totalShareholderEquity                  15 non-null     object
 34  treasuryStock                           15 non-null     object
 35  retainedEarnings                        15 non-null     object
 36  commonStock                             15 non-null     object
 37  commonStockSharesOutstanding            15 non-null     object
dtypes: object(38)
memory usage: 4.6+ KB

None

,fiscalDateEnding,reportedCurrency,totalAssets,totalCurrentAssets,cashAndCashEquivalentsAtCarryingValue,cashAndShortTermInvestments,inventory,currentNetReceivables,totalNonCurrentAssets,propertyPlantEquipment,accumulatedDepreciationAmortizationPPE,intangibleAssets,intangibleAssetsExcludingGoodwill,goodwill,investments,longTermInvestments,shortTermInvestments,otherCurrentAssets,otherNonCurrentAssets,totalLiabilities,totalCurrentLiabilities,currentAccountsPayable,deferredRevenue,currentDebt,shortTermDebt,totalNonCurrentLiabilities,capitalLeaseObligations,longTermDebt,currentLongTermDebt,longTermDebtNoncurrent,shortLongTermDebtTotal,otherCurrentLiabilities,otherNonCurrentLiabilities,totalShareholderEquity,treasuryStock,retainedEarnings,commonStock,commonStockSharesOutstanding
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1970-01-01 00:00:00.000000000,2023-06-30,USD,411976000000,184257000000,34704000000,111262000000,2500000000,48688000000,232219000000,95641000000,68251000000,77252000000,9366000000,67886000000,95599000000,9879000000,76558000000,21807000000,30601000000,205753000000,104149000000,18095000000,107626000000,5247000000,0,101604000000,12728000000,47237000000,5247000000,41990000000,47237000000,14745000000,17981000000,206223000000,None,118848000000,93718000000,7432000000
1970-01-01 00:00:00.000000001,2022-06-30,USD,364840000000,169684000000,13931000000,104757000000,3742000000,45261000000,198956000000,74398000000,59660000000,78822000000,11298000000,67524000000,95583000000,6891000000,90826000000,16924000000,21897000000,198298000000,95082000000,19000000000,96816000000,2749000000,2749000000,103216000000,11489000000,49781000000,2749000000,47032000000,49781000000,13067000000,15526000000,166542000000,None,84281000000,86939000000,7464000000
1970-01-01 00:00:00.000000002,2021-06-30,USD,333779000000,184406000000,14224000000,130334000000,2636000000,39008000000,152773000000,59715000000,51351000000,57511000000,7800000000,49711000000,122266000000,5984000000,116110000000,13393000000,15075000000,191791000000,88657000000,15163000000,88282000000,8072000000,8072000000,103134000000,9629000000,58146000000,8072000000,50074000000,58146000000,11666000000,13427000000,141988000000,None,57055000000,83111000000,7519000000
1970-01-01 00:00:00.000000003,2020-06-30,USD,301311000000,181915000000,13576000000,136527000000,1895000000,32011000000,122096000000,44151000000,43197000000,50389000000,7038000000,43351000000,130044000000,2965000000,122951000000,11482000000,13138000000,183007000000,72310000000,12530000000,78360000000,3749000000,3749000000,110697000000,7671000000,63327000000,3749000000,59578000000,63327000000,10027000000,10632000000,118304000000,None,34566000000,80552000000,7571000000
1970-01-01 00:00:00.000000004,2019-06-30,USD,286556000000,175552000000,11356000000,133819000000,2063000000,29524000000,105825000000,36477000000,35330000000,49776000000,7750000000,42026000000,129789000000,2649000000,122463000000,10146000000,14723000000,184226000000,69420000000,9382000000,74412000000,5516000000,0,108618000000,6188000000,72178000000,5516000000,66662000000,72200000000,9351000000,7581000000,102330000000,None,24150000000,78520000000,7643000000
1970-01-01 00:00:00.000000005,2018-06-30,USD,258848000000,169662000000,11946000000,133768000000,2662000000,26481000000,84300000000,29460000000,29223000000,43736000000,8053000000,35683000000,129579000000,1862000000,121822000000,6751000000,7442000000,176130000000,58488000000,8617000000,None,3998000000,0,112074000000,5568000000,76200000000,3998000000,72242000000,76200000000,8744000000,5211000000,82718000000,None,13682000000,71223000000,7677000000
1970-01-01 00:00:00.000000006,2017-06-30,USD,250312000000,162696000000,7663000000,132981000000,2181000000,19792000000,81235000000,23734000000,24179000000,45228000000,10106000000,35122000000,139004000000,6023000000,125318000000,5103000000,6076000000,162601000000,55745000000,7390000000,26656000000,10121000000,9072000000,117665000000,None,77100000000,1049000000,76073000000,86172000000,7684000000,3549000000,87711000000,None,17769000000,69315000000,7708000000
1970-01-01 00:00:00.000000007,2016-06-30,USD,193468000000,139660000000,6510000000,113240000000,2251000000,18277000000,54034000000,18356000000,19800000000,21605000000,3733000000,17872000000,123646000000,10431000000,106730000000,5892000000,3416000000,121471000000,59357000000,6898000000,None,12904000000,12904000000,74140000000,None,40600000000,0,40557000000,53504000000,5949000000,13640000000,83090000000,None,2282000000,68178000000,7808000000
1970-01-01 00:00:00.000000008,2015-06-30,USD,174472000000,122797000000,5595000000,96526000000,2902000000,17908000000,48676000000,14731000000,17606000000,21774000000,4835000000,16939000000,108579000000,12053000000,90931000000,5461000000,3117000000,94389000000,49647000000,6591000000,25318000000,7484000000,4985000000,59826000000,None,30300000000,2499000000,27808000000,35285000000,6555000000,13544000000,80083000000,None,9096000000,68465000000,8027000000
1970-01-01 00:00:00.000000009,2014-06-30,USD,172384000000,114246000000,8669000000,85709000000,2660000000,19544000000,55410000000,13011000000,14793000000,27108000000,6981000000,20127000000,100811000000,14597000000,77040000000,4392000000,3422000000,82600000000,45625000000,7432000000,25158000000,2000000000,2000000000,47485000000,None,20600000000,0,20645000000,22600000000,6906000000,11594000000,89784000000,None,17710000000,68366000000,8239000000
1970-01-01 00:00:00.000000010,2013-06-30,USD,142431000000,101466000000,3804000000,77022000000,1938000000,17486000000,39256000000,9991000000,12513000000,14655000000,3083000000,14655000000,88786000000,10844000000,73218000000,3388000000,2392000000,63487000000,37417000000,4828000000,22399000000,2999000000,0,35780000000,None,15600000000,2999000000,12601000000,15600000000,3597000000,10000000000,78944000000,None,9895000000,67306000000,8328000000
1970-01-01 00:00:00.000000011,2012-06-30,USD,121271000000,85084000000,6938000000,63040000000,1137000000,15780000000,34294000000,8269000000,10962000000,16622000000,3170000000,13452000000,129759000000,9776000000,56102000000,3092000000,1520000000,54908000000,32688000000,4175000000,20059000000,1231000000,1231000000,30428000000,None,11900000000,1231000000,10713000000,11900000000,3151000000,8208000000,66363000000,None,566000000,65797000000,8381000000
1970-01-01 00:00:00.000000012,2011-06-30,USD,108704000000,74918000000,9610000000,52772000000,1372000000,14987000000,33786000000,8162000000,9829000000,13325000000,744000000,12581000000,107332000000,10865000000,43162000000,3320000000,1434000000,51621000000,28774000000,4197000000,17120000000,0,0,30919000000,None,11900000000,0,11921000000,11900000000,3492000000,8072000000,57083000000,None,-6332000000,63415000000,8376000000
1970-01-01 00:00:00.000000013,2010-06-30,USD,86113000000,55676000000,5505000000,36788000000,740000000,13014000000,30437000000,7630000000,8629000000,12394000000,1158000000,12394000000,45068000000,7754000000,31283000000,2950000000,1501000000,39938000000,26147000000,4025000000,14830000000,1000000000,1000000000,14027000000,None,4900000000,None,4939000000,5900000000,2931000000,7445000000,46175000000,None,-16681000000,62856000000,8668000000
1970-01-01 00:00:00.000000014,2009-06-30,USD,77888000000,49280000000,6076000000,31447000000,717000000,None,28608000000,7535000000,7547000000,14262000000,1759000000,12503000000,None,4933000000,25371000000,3711000000,1599000000,38330000000,27034000000,3324000000,14284000000,None,2000000000,11296000000,None,3756000000,None,3746000000,5746000000,3142000000,6269000000,39558000000,None,-22824000000,62382000000,8908000000

In [75]:
v1=balsheetDF[["fiscalDateEnding","totalAssets", "totalLiabilities", "deferredRevenue"]]
display(v1)
display(balsheetDF.iloc[[0,2,3],[2,3,4]])
balsheetDF.index
balsheetDF.loc[["1970-01-01 00:00:00.000000000","1970-01-01 00:00:00.000000001"],["fiscalDateEnding"]]

,fiscalDateEnding,totalAssets,totalLiabilities,deferredRevenue
date,,,,
1970-01-01 00:00:00.000000000,2023-06-30,411976000000,205753000000,107626000000
1970-01-01 00:00:00.000000001,2022-06-30,364840000000,198298000000,96816000000
1970-01-01 00:00:00.000000002,2021-06-30,333779000000,191791000000,88282000000
1970-01-01 00:00:00.000000003,2020-06-30,301311000000,183007000000,78360000000
1970-01-01 00:00:00.000000004,2019-06-30,286556000000,184226000000,74412000000
1970-01-01 00:00:00.000000005,2018-06-30,258848000000,176130000000,None
1970-01-01 00:00:00.000000006,2017-06-30,250312000000,162601000000,26656000000
1970-01-01 00:00:00.000000007,2016-06-30,193468000000,121471000000,None
1970-01-01 00:00:00.000000008,2015-06-30,174472000000,94389000000,25318000000
1970-01-01 00:00:00.000000009,2014-06-30,172384000000,82600000000,25158000000
1970-01-01 00:00:00.000000010,2013-06-30,142431000000,63487000000,22399000000
1970-01-01 00:00:00.000000011,2012-06-30,121271000000,54908000000,20059000000
1970-01-01 00:00:00.000000012,2011-06-30,108704000000,51621000000,17120000000
1970-01-01 00:00:00.000000013,2010-06-30,86113000000,39938000000,14830000000
1970-01-01 00:00:00.000000014,2009-06-30,77888000000,38330000000,14284000000

,totalAssets,totalCurrentAssets,cashAndCashEquivalentsAtCarryingValue
date,,,
1970-01-01 00:00:00.000000000,411976000000,184257000000,34704000000
1970-01-01 00:00:00.000000002,333779000000,184406000000,14224000000
1970-01-01 00:00:00.000000003,301311000000,181915000000,13576000000

                              fiscalDateEnding
date
1970-01-01 00:00:00.000000000       2023-06-30
1970-01-01 00:00:00.000000001       2022-06-30

In [40]:
dict={"name":["john","setra","batman"],
      "title":["doe","the imperishable","defender of gotham"]}
df1 = pd.DataFrame(dict)
display(df1)

     name               title
0    john                 doe
1   setra    the imperishable
2  batman  defender of gotham

In [44]:
lst1 = [1,2,3,4,5]
srs1 = pd.Series(lst1)
srs1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [78]:
balsheetDFI = balsheetDF.set_index("fiscalDateEnding")
balsheetDFI

,reportedCurrency,totalAssets,totalCurrentAssets,cashAndCashEquivalentsAtCarryingValue,cashAndShortTermInvestments,inventory,currentNetReceivables,totalNonCurrentAssets,propertyPlantEquipment,accumulatedDepreciationAmortizationPPE,intangibleAssets,intangibleAssetsExcludingGoodwill,goodwill,investments,longTermInvestments,shortTermInvestments,otherCurrentAssets,otherNonCurrentAssets,totalLiabilities,totalCurrentLiabilities,currentAccountsPayable,deferredRevenue,currentDebt,shortTermDebt,totalNonCurrentLiabilities,capitalLeaseObligations,longTermDebt,currentLongTermDebt,longTermDebtNoncurrent,shortLongTermDebtTotal,otherCurrentLiabilities,otherNonCurrentLiabilities,totalShareholderEquity,treasuryStock,retainedEarnings,commonStock,commonStockSharesOutstanding
fiscalDateEnding,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-06-30,USD,411976000000,184257000000,34704000000,111262000000,2500000000,48688000000,232219000000,95641000000,68251000000,77252000000,9366000000,67886000000,95599000000,9879000000,76558000000,21807000000,30601000000,205753000000,104149000000,18095000000,107626000000,5247000000,0,101604000000,12728000000,47237000000,5247000000,41990000000,47237000000,14745000000,17981000000,206223000000,None,118848000000,93718000000,7432000000
2022-06-30,USD,364840000000,169684000000,13931000000,104757000000,3742000000,45261000000,198956000000,74398000000,59660000000,78822000000,11298000000,67524000000,95583000000,6891000000,90826000000,16924000000,21897000000,198298000000,95082000000,19000000000,96816000000,2749000000,2749000000,103216000000,11489000000,49781000000,2749000000,47032000000,49781000000,13067000000,15526000000,166542000000,None,84281000000,86939000000,7464000000
2021-06-30,USD,333779000000,184406000000,14224000000,130334000000,2636000000,39008000000,152773000000,59715000000,51351000000,57511000000,7800000000,49711000000,122266000000,5984000000,116110000000,13393000000,15075000000,191791000000,88657000000,15163000000,88282000000,8072000000,8072000000,103134000000,9629000000,58146000000,8072000000,50074000000,58146000000,11666000000,13427000000,141988000000,None,57055000000,83111000000,7519000000
2020-06-30,USD,301311000000,181915000000,13576000000,136527000000,1895000000,32011000000,122096000000,44151000000,43197000000,50389000000,7038000000,43351000000,130044000000,2965000000,122951000000,11482000000,13138000000,183007000000,72310000000,12530000000,78360000000,3749000000,3749000000,110697000000,7671000000,63327000000,3749000000,59578000000,63327000000,10027000000,10632000000,118304000000,None,34566000000,80552000000,7571000000
2019-06-30,USD,286556000000,175552000000,11356000000,133819000000,2063000000,29524000000,105825000000,36477000000,35330000000,49776000000,7750000000,42026000000,129789000000,2649000000,122463000000,10146000000,14723000000,184226000000,69420000000,9382000000,74412000000,5516000000,0,108618000000,6188000000,72178000000,5516000000,66662000000,72200000000,9351000000,7581000000,102330000000,None,24150000000,78520000000,7643000000
2018-06-30,USD,258848000000,169662000000,11946000000,133768000000,2662000000,26481000000,84300000000,29460000000,29223000000,43736000000,8053000000,35683000000,129579000000,1862000000,121822000000,6751000000,7442000000,176130000000,58488000000,8617000000,None,3998000000,0,112074000000,5568000000,76200000000,3998000000,72242000000,76200000000,8744000000,5211000000,82718000000,None,13682000000,71223000000,7677000000
2017-06-30,USD,250312000000,162696000000,7663000000,132981000000,2181000000,19792000000,81235000000,23734000000,24179000000,45228000000,10106000000,35122000000,139004000000,6023000000,125318000000,5103000000,6076000000,162601000000,55745000000,7390000000,26656000000,10121000000,9072000000,117665000000,None,77100000000,1049000000,76073000000,86172000000,7684000000,3549000000,87711000000,None,17769000000,69315000000,7708000000
2016-06-30,USD,193468000000,139660000000,6510000000,113240000000,2251000000,18277000000,54034000000,18356000000,19800000000,21605000000,3733000000,17872000000,123646000000,10431000000,106730000000,5892000000,3416000000,121471000000,59357000000,6898000000,None,12904000000,12904000000,74140000000,None,40600000000,0,40557000000,53504000000,5949000000,13640000000,83090000000,None,2282000000,68178000000,7808000000
2015-06-30,USD,174472000000,122797000000,5595000000,96526000000,2902000000,17908000000,48676000000,14731000000,17606000000,21774000000,4835000000,16939000000,108579000000,12053000000,90931000000,5461000000,3117000000,94389000000,49647000000,6591000000,25318000000,7484000000,4985000000,59826000000,None,30300000000,2499000000,27808000000,35285000000,6555000000,13544000000,80083000000,None,9096000000,68465000000,8027000000
2014-06-30,USD,172384000000,114246000000,8669000000,85709000000,2660000000,19544000000,55410000000,13011000000,14793000000,27108000000,6981000000,20127000000,100811000000,14597000000,77040000000,4392000000,3422000000,82600000000,45625000000,7432000000,25158000000,2000000000,2000000000,47485000000,None,20600000000,0,20645000000,22600000000,6906000000,11594000000,89784000000,None,17710000000,68366000000,8239000000
2013-06-30,USD,142431000000,101466000000,3804000000,77022000000,1938000000,17486000000,39256000000,9991000000,12513000000,14655000000,3083000000,14655000000,88786000000,10844000000,73218000000,3388000000,2392000000,63487000000,37417000000,4828000000,22399000000,2999000000,0,35780000000,None,15600000000,2999000000,12601000000,15600000000,3597000000,10000000000,78944000000,None,9895000000,67306000000,8328000000
2012-06-30,USD,121271000000,85084000000,6938000000,63040000000,1137000000,15780000000,34294000000,8269000000,10962000000,16622000000,3170000000,13452000000,129759000000,9776000000,56102000000,3092000000,1520000000,54908000000,32688000000,4175000000,20059000000,1231000000,1231000000,30428000000,None,11900000000,1231000000,10713000000,11900000000,3151000000,8208000000,66363000000,None,566000000,65797000000,8381000000
2011-06-30,USD,108704000000,74918000000,9610000000,52772000000,1372000000,14987000000,33786000000,8162000000,9829000000,13325000000,744000000,12581000000,107332000000,10865000000,43162000000,3320000000,1434000000,51621000000,28774000000,4197000000,17120000000,0,0,30919000000,None,11900000000,0,11921000000,11900000000,3492000000,8072000000,57083000000,None,-6332000000,63415000000,8376000000
2010-06-30,USD,86113000000,55676000000,5505000000,36788000000,740000000,13014000000,30437000000,7630000000,8629000000,12394000000,1158000000,12394000000,45068000000,7754000000,31283000000,2950000000,1501000000,39938000000,26147000000,4025000000,14830000000,1000000000,1000000000,14027000000,None,4900000000,None,4939000000,5900000000,2931000000,7445000000,46175000000,None,-16681000000,62856000000,8668000000
2009-06-30,USD,77888000000,49280000000,6076000000,31447000000,717000000,None,28608000000,7535000000,7547000000,14262000000,1759000000,12503000000,None,4933000000,25371000000,3711000000,1599000000,38330000000,27034000000,3324000000,14284000000,None,2000000000,11296000000,None,3756000000,None,3746000000,5746000000,3142000000,6269000000,39558000000,None,-22824000000,62382000000,8908000000